services:
  postgres:
    image: 'postgres:latest'
    container_name: urldbdocker
    environment:
      - 'POSTGRES_DB=urlshortener'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=root'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - url-network

  backend:
    build:
      context: ./backend
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/urlshortener
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - postgres
    networks:
      - url-network

networks:
  url-network:
    driver: bridge

volumes:
  postgres-data: